[package]
name = "crud_app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
utoipa = "5"
utoipa-swagger-ui = { version = "9", features = ["actix-web"] }